config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :directors
  resources :orders do 
    collection do 
      get :express
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'users/invitations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  
  get "users/express"

  put   'productions/:production_id/update_director'   =>  'productions#update_director',    as: :update_production_director
  get '/auth/:provider/callback' => 'users#oauth_login'

  get 'invitations/new', to: 'invitations#new'
  post 'invitations', to: 'invitations#create', as: 'invitations'
  get '/invitations', to: 'invitations#index'
  resources :resumes do
    collection do
      get :email_resume
      
      get :find_user_role
      get :account_tier
      get :new_theatre
      post :new_theatre
      get :page_view
    end
    member do
      get :download_pdf
      get :show_resume_pdf
    end  
    resources :roles

  end
  resources :roles
  
  post   '/sort_sections'      => 'resumes#sort_sections',      :as => 'sort_sections'

  get    '/resumes/view_resume_pdf/:id'  => 'resumes#view_resume_pdf', :as => 'view_resume_pdf'
  get    '/resumes/:id/edit/:role_id'  => 'resumes#edit_with_role', :as => 'edit_resume_with_role'
  post   '/resumes/:id/add_table'      => 'resumes#add_table',      :as => 'add_resume_table'
  delete '/resumes/:id/destroy_table/:table_id'  => 'resumes#destroy_table',  :as => 'destroy_resume_table'
  post   '/upload'=> 'resumes#upload', :as => 'upload'
  post   '/autosuggest'=> 'resumes#autosuggest', :as => 'autosuggest'

  get 'users' => 'users#index', :as => 'users'
  get 'users/:id' => 'users#show', :as => 'profile'
  get  '/add_frineds'  => 'users#add_frineds', :as => 'add_frineds'

  resources :shows

  resources :productions do
    resources :shows
    resources :roles
    resources :director_invitations
    resources :artist_invitations
    collection do
      get :find_company
    end
  end

  resources :users do
    resources :artist_invitations
  end

  resources :rtables do
    resources :rtable_items
  end

  resources :education_tables do
    resources :rtable_items
  end

  resources :companies do
    resources :artist_invitations
  end

  resources :venues do
    resources :artist_invitations
  end
  get  '/venues/:name'  => 'venues#show', :as => 'venue_show'

  post 'section_slots' => 'section_slots#sort', :as => 'sort_section_slots'
  get  '/paypal_url'  => 'home#paypal_url', :as => 'paypal_url'
  get  '/about'  => 'home#about', :as => 'about'
  get  '/faq'  => 'home#faq', :as => 'faq'
  get  '/terms_and_conditions'  => 'home#terms_and_conditions', :as => 'terms_and_conditions'
  get  '/contact'  => 'home#contact', :as => 'contact'
  get  '/privacy'  => 'home#privacy', :as => 'privacy'
  get  '/copyright'  => 'home#copyright', :as => 'copyright'

  match "/404", :to => "errors#file_not_found", via: 'get'
  delete '/remove_video/:id'  => 'resumes#remove_video',:as => 'destroy_resume_video'
  post 'add_videos' => 'resumes#add_videos',:as=>'add_videos'
  post 'create_role' => 'resumes#create_role',:as=>'create_role'

  post '/artist_invitations/add_nested_invitations' => 'artist_invitations#add_nested_invitations'
end

app/views/layouts/includes/_actor_widget_3c.html.erb
<% c = ContactInfo.find_by(:resume_id => role.resume_id)  %>
<% if !c.nil? %>
<div class="col-md-3 m-bottom-20">
  <div class="" style="width: 180px; height: 180px; background-image: url('/images/fallback/silhouette-180.jpg')"></div>
  <!-- <h5><%#= link_to role.user_name, '#' %></h5>
  <p> <em><%#= role.name %></em> </p> -->
  <h5><%= link_to c.nick_name, resume_path(role.resume_id) %></h5>
  <p> <em><%= role.name %></em> </p>
</div>
<% end %>

app/views/layouts/includes/_actor_widgets_row.html.erb
<% [4, roles.length].min.times do |i| %>
  <%= render partial: 'layouts/includes/actor_widget_3c', locals: {role: roles.shift} %>
<% end %>

app/views/layouts/includes/_error_explanation.html.erb
<div class="error_explanation" style="display: <%= display || 'none' %>">
  <div class="row">
    <div class="col-md-offset-<%= offset %> col-md-<%= span %>">
      <ul id="error_list" style="list-style-type: none; padding-left: 13px; color: #fe4748">
        <% if entity.errors.any? %>
          <% entity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/includes/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=1632386703747533";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<h3>Invite Artists to Artist Magnet with Facebook</h3>

<h4>Click the Send button to invite your Facebook friends
to join Artist Magnet</h4>
<div class="fb-send" data-href="http://www.ArtistMagnet.com"></div>

<h4>Click the Share button to share Artist Magnet on your Facebook timeline, your friends'
timelines, your groups, your pages, and private messages</h4>
<div class="fb-share-button" data-href="http://www.ArtistMagnet.com" data-layout="button_count" data-mobile-iframe="true"></div>

app/views/layouts/includes/_footer.html.erb
<footer class="line">
  <div class="footer-container">
    <div class="btn_l">
      <%= link_to 'copyright 2016@ArtistMagnet', "/copyright" %>
    </div>
    <div class="btn_r">
      <%= link_to 'About Us', "/about" %>
      /
      <%= link_to 'Contact Us', "/contact" %>
      /
      <%= link_to 'FAQ', "/faq" %>
      /
      <%= link_to 'Terms and Conditions', "/terms_and_conditions" %>
    </div>		 
  </div>
</footer>

app/views/layouts/includes/_notice.html.erb
<% if !flash[:alert].blank? || !notice.blank? ||  !flash[:notice].blank? %>
	<div class="alert " id="notice">
	  <button type="button" class="close">×</button>
	  <%= flash[:alert] %>
	  <%= notice %>
	  <%#= flash[:notice] %>
	</div>
<% end %>

app/views/layouts/includes/_production_director.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <h4>
              <span>Director</span>
              <%= link_to production_director_invitations_path(production) do %>
                <button class="btn btn-primary pull-right m-top-m6" type="button"> <%= @production.director_name.nil? ? 'Add Director' : 'Change Director' %></button>
              <% end %>
            </h4>
            <% if production.director_id.nil? %>
              <%= production.director_name %>
            <% else %>
              <%= link_to production.director_name, production.director %>
              <br />

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/includes/_production_widget_4c.html.erb
<div class="col-md-4 m-bottom-20">
  <%= link_to(production) do %>
    <div class="" style="width: 180px; height: 180px; background-image: url('/images/fallback/curtain-180.jpg')"></div>
    <h5 class="text-primary"><%= production.name %></h5>
  <% end %>
    <p> <em><%= Show.find_by(:production_id => production.id).date.strftime("%b %-d, %Y") %></em> </p>
    <% if params[:controller] != 'venues'  %>
      <% venue = production.current_venue %>
      <%= link_to venue.name, venue_path(venue.id) %>
      <br />
    <% else %>
      <% company = Company.find_by(:id => production.company_id) %>
      <%= link_to company.name, company_path(company.id) %>
      <br />
    <% end %>
</div>

app/views/layouts/includes/_production_widgets_row.html.erb
<% [3, productions.length].min.times do |i| %>
  <%= render partial: 'layouts/includes/production_widget_4c', locals: {production: productions.shift} %>
<% end %>

app/views/layouts/includes/_sidebar.html.erb
<!-- LEFT COLUMN -->
<div class="logo-box">
  <a href="<%=root_path%>" ><img src="/assets/logo.svg"></a>
</div>
<% if user_signed_in? %> 
  <div class="artist_box">
    <div align="center">
      <% if current_user.gender and current_user.gender.downcase == 'male' %>
        <img src="/assets/cast and crew - male.jpg"  class="simg_atist" alt="Actor">
      <% else %>
        <img src="/assets/cast and crew - female.jpg"  class="simg_atist" alt="Actor">
      <% end %>
    </div>
  </div>
  <div class="aside-nav">
    <ul class="chevron">
      <li>
        <a>Resumes</a>
        <ul>
          <% @resumes.each do |resume| %>
            <li>
              <%= link_to resume, id: "resume-#{resume.id}-link" do %>
                <%= resume.resume_name %>
              <% end %>
            </li>
          <% end %>
        </ul>					
      </li>
      <li>
      <% if current_user.subscription || @resumes.count == 0 %> 
        <%= link_to 'Build A Resume', new_resume_path %>
      <% else %>
        <a href="#" onclick="$('#upgradeModal').modal('show')">Build A Resume</a>
      <% end %>
      </li>
      <li><a href="/invitations">Add Friends</a></li>
      <li><a href="#" onclick="$('#upgradeModal').modal('show')">Become a PowerMagnet</a></li>
      <li><%= link_to "Manage Resumes",  resumes_path %></li>
      <li><a>Account Settings</a>
        <ul>
          <li><a href="<%=edit_user_registration_path%>">Edit Profile</a></li>
          <li><a href="#">Update Password</a></li>
        </ul>
      </li>
      <li><a href="/users/sign_out"  data-method="delete" rel="nofollow">Log out</a></li>


    </ul>
    <div id="search" class="line" >
      <div class="search-bar">
        <form>
          <input class="s-11 sfield" name="" placeholder="Search" title="Search" type="text" />
          <input type="image" class="searchbutton" name="search" src="http://www.spheretekk.com/bc/images/search-icon.gif" alt="Search">
              <!--<a class="s-1" style="padding-left: 10px;" ><i class="icon-magnifying"></i></a>-->
        </form>	 
      </div>
    </div>
  </div>
<% end %>



<div class="modal " id="upgradeModal" tabindex="-1" role="dialog" 
     aria-labelledby="upgradeModalLabel" aria-hidden="true">
     <div class="modal-dialog">
        <div class="modal-content">
           <div class="modal-header">
              <button type="button" class="close" 
                 data-dismiss="modal" aria-hidden="true">
                    &times;
              </button>
              <h4 class="modal-title" id="myModalLabel" title="Become a PowerMagnet">
                 Become a PowerMagnet
              </h4>
           </div>
           <div class="modal-body">
		<%= render :file => 'resumes/account_tier' %>
	
           </div>
           <div class="modal-footer">
           </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal -->
    </div>

app/views/layouts/includes/_signin.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name),:html=>{:class=>"form-inline"}) do |f| %>
  <div class="row">
    <div class="form-group col-xs-8 col-lg-9">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <%= f.email_field :email, autofocus: true,:class=>"form-control only-bottom-border slategrey-border" ,:id=>"exampleInputName2" ,:placeholder=>"email" %>
        </div>
        <div class="col-xs-12 col-md-6">
          <%= f.password_field :password, autocomplete: "off",:class=>"form-control only-bottom-border slategrey-border" ,:id=>"exampleInputEmail2" ,:placeholder=>"password"%>
        </div>
        <% if devise_mapping.rememberable? -%>
          <div class="col-xs-12">
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
          </div>
        <% end -%>
      </div>
    </div>
    <div class="col-xs-4 col-lg-3">
      <div class="row">
        <div class="col-xs-12">
          <%= f.submit "Log in", id: 'login-btn', :class=>"btn slategrey black-shadow" %>
        </div>
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
          <div class="col-xs-12">
            <%= link_to "forgot password?", new_password_path(resource_name), class: 'small-text' %>
          </div>
        <% end -%>
      </div>
    </div>
    
  </div>
  
  <div class="row">
    
  </div>
<%end%>

app/views/layouts/includes/_socialicon.html.erb
<%# address %>
<%# css-class %>
<% unless address.blank? %>
  <%= link_to(address) do %>
    <i class="<%= css_class %>"></i>
  <% end %>
<% end %>

app/views/layouts/includes/_socialicons.html.erb
<a class="social-share-button-facebook" data-site="facebook" href="#" onclick="return SocialShareButton.share(this);" rel="nofollow " title="Share to Facebook">
  <span class="fa-stack fa-lg">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
  </span>
</a>
<a class="social-share-button-twitter" data-site="twitter" href="#" onclick="return SocialShareButton.share(this);" rel="nofollow " title="Share to Twitter">
  <span class="fa-stack fa-lg">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
  </span>
</a>
<a class="social-share-button-tumblr" data-site="tumblr" href="#" onclick="return SocialShareButton.share(this);" rel="nofollow " title="Share to Tumblr">
  <span class="fa-stack fa-lg">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-tumblr fa-stack-1x fa-inverse"></i>
  </span>
</a>
<a class="social-share-button-linkedin" data-site="linkedin" href="#" onclick="return SocialShareButton.share(this);" rel="nofollow " title="Share to Linkedin">
  <span class="fa-stack fa-lg">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-linkedin-square fa-stack-1x fa-inverse"></i>
  </span>
</a>