config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :directors
  resources :orders do 
    collection do 
      get :express
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'users/invitations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  
  get "users/express"

  put   'productions/:production_id/update_director'   =>  'productions#update_director',    as: :update_production_director
  get '/auth/:provider/callback' => 'users#oauth_login'

  get 'invitations/new', to: 'invitations#new'
  post 'invitations', to: 'invitations#create', as: 'invitations'
  get '/invitations', to: 'invitations#index'
  resources :resumes do
    collection do
      get :email_resume
      
      get :find_user_role
      get :account_tier
      get :new_theatre
      post :new_theatre
      get :page_view
    end
    member do
      get :download_pdf
      get :show_resume_pdf
    end  
    resources :roles

  end
  resources :roles
  
  post   '/sort_sections'      => 'resumes#sort_sections',      :as => 'sort_sections'

  get    '/resumes/view_resume_pdf/:id'  => 'resumes#view_resume_pdf', :as => 'view_resume_pdf'
  get    '/resumes/:id/edit/:role_id'  => 'resumes#edit_with_role', :as => 'edit_resume_with_role'
  post   '/resumes/:id/add_table'      => 'resumes#add_table',      :as => 'add_resume_table'
  delete '/resumes/:id/destroy_table/:table_id'  => 'resumes#destroy_table',  :as => 'destroy_resume_table'
  post   '/upload'=> 'resumes#upload', :as => 'upload'
  post   '/autosuggest'=> 'resumes#autosuggest', :as => 'autosuggest'

  get 'users' => 'users#index', :as => 'users'
  get 'users/:id' => 'users#show', :as => 'profile'
  get  '/add_frineds'  => 'users#add_frineds', :as => 'add_frineds'

  resources :shows

  resources :productions do
    resources :shows
    resources :roles
    resources :director_invitations
    resources :artist_invitations
    collection do
      get :find_company
    end
  end

  resources :users do
    resources :artist_invitations
  end

  resources :rtables do
    resources :rtable_items
  end

  resources :education_tables do
    resources :rtable_items
  end

  resources :companies do
    resources :artist_invitations
  end

  resources :venues do
    resources :artist_invitations
  end
  get  '/venues/:name'  => 'venues#show', :as => 'venue_show'

  post 'section_slots' => 'section_slots#sort', :as => 'sort_section_slots'
  get  '/paypal_url'  => 'home#paypal_url', :as => 'paypal_url'
  get  '/about'  => 'home#about', :as => 'about'
  get  '/faq'  => 'home#faq', :as => 'faq'
  get  '/terms_and_conditions'  => 'home#terms_and_conditions', :as => 'terms_and_conditions'
  get  '/contact'  => 'home#contact', :as => 'contact'
  get  '/privacy'  => 'home#privacy', :as => 'privacy'
  get  '/copyright'  => 'home#copyright', :as => 'copyright'

  match "/404", :to => "errors#file_not_found", via: 'get'
  delete '/remove_video/:id'  => 'resumes#remove_video',:as => 'destroy_resume_video'
  post 'add_videos' => 'resumes#add_videos',:as=>'add_videos'
  post 'create_role' => 'resumes#create_role',:as=>'create_role'

  post '/artist_invitations/add_nested_invitations' => 'artist_invitations#add_nested_invitations'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :productions
  has_many :theatres
  has_many :simple_invitations, :as => :to

  #validates :name, :uniqueness => true
  validate :validate_properties
  validates :email, :primary_contact_email, :email => true
  validates :website, :addr_fb, :addr_tw, uri: true
  has_one :photo, as: :imageable, dependent: :destroy
  has_many :invitations,:as => :to

  #has_many :photos, as: :imageable
  # has_one :photo, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :photo,:allow_destroy => true, reject_if: :all_blank
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/fallback/union_station-180.png"
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  accepts_nested_attributes_for :simple_invitations, allow_destroy: true

  def validate_properties
    if name.blank?
      errors.add :name, "is required"
    end

    if primary_contact_name.blank?
      errors.add :primary_contact_name, "is required"
    end

    if city.blank?
      errors.add :city, "is required"
    end

    if country == 'United States' && state.blank?
      errors.add :state, "is required"
    end

    if country.blank?
      errors.add :country, "is required"
    end

  end


  def name_with_city
    city.blank? ? name : [name, city].join(', ')
  end

  # def city
  #   productions.each do |production|
  #     return production.city unless production.city.nil?
  #   end
  # end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.order(:name)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new(:name=>params[:name])
    respond_to do |format|
      format.js
    end
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        # flash[:notice] ='Company was successfully created.'
        # format.js
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, location: @company }
      else
        # format.js { render :new }
        format.html { render :new }
        format.json { render json: {error: @company.errors.full_messages}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render json: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address1, :address2, :city, :zipcode, :state, :country, :primary_contact_name, :primary_contact_email, :primary_contact_phone, :year_founded, :description, :email, :addr_fb, :addr_tw, :website, :phone,:photo_attributes=>[:image])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="panel panel-default" >

  <div class="panel-body">
    <h3 class="col-md-offset-4 col-md-8 m-bottom-20">
      <span>Add a new Company</span>
      <a class="pull-right back-link" href="javascript:void(0)" >
        <i class="fa fa-undo"></i>
      </a>
    </h3>

  <%= form_for(@company, remote: true,format: :json, html: {"data-type" => :json,:multipart=>true,class: 'company_form form-horizontal'}) do |f| %>
     <%= render 'layouts/includes/error_explanation', entity: @company, offset: 4, span: 8 %>

    <div class="panel-body">
      <div class="form-group">
        <div class="field">
          <%= f.label :name, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :name, {class: 'form-control', placeholder: 'Enter Name'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :year_founded, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :year_founded, {class: 'form-control', placeholder: 'Enter Year'} %>
            <%# f.select :year_founded, (1950..Time.now.year).collect {|y| [y, y] }, {include_blank: true, placeholder: 'Enter Year'}, {class: 'form-control essential chosen-select'} %>
            <%# select_tag  'venue[year_founded]', options_for_select([1950..Time.now.year], ""), {class: 'form-control essential chosen-select'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :address1, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :address1 , {class: 'form-control', placeholder: 'Enter Address'}%>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :address2, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :address2, {class: 'form-control', placeholder: 'Enter Address (cont.)'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
        <%= f.fields_for :photo do |img| %>
          <%= img.label :image, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= img.file_field :image %>
            
          </div>
          <%end%>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :city, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :city, {class: 'form-control', placeholder: 'Enter City'} %>
          </div>
        </div>
      </div>
      <!-- <div class="form-group">
        <%#= f.fields_for :photo do |g| %>
          <div class="field">
          <%#= g.label :image, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%#= g.file_field :image, {class: 'form-control'} %>
          </div>
        </div>
        <%#end%>
      </div> -->
      <div class="form-group">
        <div class="field">
          <%= f.label :zipcode, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :zipcode, {class: 'form-control', placeholder: 'Enter ZIP code'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :state, {class: "col-sm-4 control-label semi-mandatory", title: "Required for US companies"} %>
          <div class="col-sm-8">
            <%= select_tag 'company[state]', options_for_select(Topo.us_state_options), {class: 'form-control essential chosen-select', prompt: '--'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :country, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= select_tag  'company[country]', options_for_select(Topo.country_options, "United States"), {class: 'form-control essential chosen-select'} %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= f.label :primary_contact_name, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :primary_contact_name, {class: 'form-control', placeholder: 'Enter Primary contact name'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :primary_contact_email, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :primary_contact_email, {class: 'form-control', placeholder: 'Enter Primary contact email'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :primary_contact_phone, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field  :primary_contact_phone, {class: 'form-control', placeholder: 'Enter Primary contact phone'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :description, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_area :description, {class: 'form-control', placeholder: 'Enter Description'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :email, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field :email, {class: 'form-control', placeholder: 'Enter Email'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :phone, {class: "col-sm-4 control-label"} %>
          <div class="col-sm-8">
            <%= f.text_field :phone, {class: 'form-control', placeholder: 'Enter Phone'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :addr_fb, {class: "col-sm-4 control-label", title: "Will be used as link. Use a valid page address"} %>
          <div class="col-sm-8">
            <%= f.text_field :addr_fb, {class: 'form-control', placeholder: 'Enter Facebook page address'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :addr_tw, {class: "col-sm-4 control-label", title: "Please enter an address beginning with http:// or https://"} %>
          <div class="col-sm-8">
            <%= f.text_field :addr_tw, {class: 'form-control', placeholder: 'Enter Twitter page address'} %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label :website, {class: "col-sm-4 control-label", title: "Please enter an address beginning with http:// or https://"} %>
          <div class="col-sm-8">
            <%= f.text_field :website, {class: 'form-control', placeholder: 'Enter website address'} %>
          </div>
        </div>
      </div>
       
      <div class="actions form-group">
        <div class="col-sm-8 pull-right">
          <%= f.button 'Done', {class: "company-btn btn btn-primary m-top-m6"} %>
          <%# f.submit %>
        </div>
      </div>

    </div>
  <% end %>
  </div>
</div>
<script type="text/javascript">
  $('.company-btn').click(function(e) {
    e.preventDefault();
    $('.company_form').submit();
  });
</script>

app/views/companies/create.js.erb
// window.location.reload();
$("#myModal").modal("hide");
$("#add-new-company").hide();
$(".company_name").val("<%=@company.name%>")
$('.flash-message').html("<%= escape_javascript render('layouts/includes/notice') %>");

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Primary contact name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.primary_contact_name %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/new.js.erb
$("#myModal").modal("show");
$('.modal-body').html("<%= escape_javascript render('form') %>");

app/views/companies/show.html.erb
<div class="box">
  <!-- HEADER -->     
  <div class="line">
    <section>
      <div class="line">
        <div class="line">
          <div class="margin">
            <div class="s-12 l-8">
              <div class="box_text_container">
                <h4><%= @company.name %></h4>
                <% unless @company.year_founded.blank? %>
                  <div>
                    Founded: <%= @company.year_founded %>
                  </div>
                <% end %>
                <% unless @company.website.blank? %>
                  <%= link_to @company.website %>
                  <br><br>
                <% end %>
                <% unless @company.primary_contact_phone.blank? %>
                  <%= @company.primary_contact_phone %> <br />
                <% end %>
                <% unless @company.primary_contact_email.blank? %>
                  <a href="mailto:<%= @company.primary_contact_email %>"><%= @company.primary_contact_email %></a>
                  <br><br>
                <% end %>
                
              </div>
										
              <%= link_to  company_artist_invitations_path @company do %>
                <button class="btn_auk" type="button">Add Artists</button>
              <% end %><br>

              <div class="social-share-button" data-title="<%= @company.name %>" data-img=<%= image_url 'company_md.jpg' %> data-popup="true">
                <%= render 'layouts/includes/socialicons' %>
              </div>
            </div>
            <div class="s-12 l-4 rocket_block_container">
              <%if @company.photo && @company.photo.try(:image).present? %>
                <%=image_tag @company.photo.image(:medium), class: "rocket_bock_a" %>
              <%else%>
                <%=image_tag 'company_md.jpg', class: "rocket_bock_a" %>
              <%end%>
            </div>
            
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
		
			   
<div class="box last_box">
  <!-- HEADER -->     
  <div class="line">
    <section>
      <h3>Productions</h3>
      <div class="line">
        <div class="line">
          <div class="margin">                               
            <center>
              <% productions = @company.productions.select('productions.*, shows.date').joins(:shows).order('shows.date desc').uniq %>
              <% productions.each do |production| %>
                <%= link_to(production) do %>
                  <div class="s-12 l-3">
                    <%=image_tag 'Production_md.jpg', class: 'img_crew'%>
                    <h4 class="title_production"><%= production.name %></h4>
                    <p><%= link_to production.shows.last.venue.name, production.shows.last.venue %></p>
                    <p class="p_box_a"><%= production.shows.last.date.strftime("%b %-d, %Y") %></p>
                  </div>	
                <% end %>
              <% end %>				
            </center>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>