config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :directors
  resources :orders do 
    collection do 
      get :express
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => 'users/invitations', :passwords => 'users/passwords', :sessions => 'users/sessions' }
  
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  
  get "users/express"

  put   'productions/:production_id/update_director'   =>  'productions#update_director',    as: :update_production_director
  get '/auth/:provider/callback' => 'users#oauth_login'

  get 'invitations/new', to: 'invitations#new'
  post 'invitations', to: 'invitations#create', as: 'invitations'
  get '/invitations', to: 'invitations#index'
  resources :resumes do
    collection do
      get :email_resume
      
      get :find_user_role
      get :account_tier
      get :new_theatre
      post :new_theatre
      get :page_view
    end
    member do
      get :download_pdf
      get :show_resume_pdf
    end  
    resources :roles

  end
  resources :roles
  
  post   '/sort_sections'      => 'resumes#sort_sections',      :as => 'sort_sections'

  get    '/resumes/view_resume_pdf/:id'  => 'resumes#view_resume_pdf', :as => 'view_resume_pdf'
  get    '/resumes/:id/edit/:role_id'  => 'resumes#edit_with_role', :as => 'edit_resume_with_role'
  post   '/resumes/:id/add_table'      => 'resumes#add_table',      :as => 'add_resume_table'
  delete '/resumes/:id/destroy_table/:table_id'  => 'resumes#destroy_table',  :as => 'destroy_resume_table'
  post   '/upload'=> 'resumes#upload', :as => 'upload'
  post   '/autosuggest'=> 'resumes#autosuggest', :as => 'autosuggest'

  get 'users' => 'users#index', :as => 'users'
  get 'users/:id' => 'users#show', :as => 'profile'
  get  '/add_frineds'  => 'users#add_frineds', :as => 'add_frineds'

  resources :shows

  resources :productions do
    resources :shows
    resources :roles
    resources :director_invitations
    resources :artist_invitations
    collection do
      get :find_company
    end
  end

  resources :users do
    resources :artist_invitations
  end

  resources :rtables do
    resources :rtable_items
  end

  resources :education_tables do
    resources :rtable_items
  end

  resources :companies do
    resources :artist_invitations
  end

  resources :venues do
    resources :artist_invitations
  end
  get  '/venues/:name'  => 'venues#show', :as => 'venue_show'

  post 'section_slots' => 'section_slots#sort', :as => 'sort_section_slots'
  get  '/paypal_url'  => 'home#paypal_url', :as => 'paypal_url'
  get  '/about'  => 'home#about', :as => 'about'
  get  '/faq'  => 'home#faq', :as => 'faq'
  get  '/terms_and_conditions'  => 'home#terms_and_conditions', :as => 'terms_and_conditions'
  get  '/contact'  => 'home#contact', :as => 'contact'
  get  '/privacy'  => 'home#privacy', :as => 'privacy'
  get  '/copyright'  => 'home#copyright', :as => 'copyright'

  match "/404", :to => "errors#file_not_found", via: 'get'
  delete '/remove_video/:id'  => 'resumes#remove_video',:as => 'destroy_resume_video'
  post 'add_videos' => 'resumes#add_videos',:as=>'add_videos'
  post 'create_role' => 'resumes#create_role',:as=>'create_role'

  post '/artist_invitations/add_nested_invitations' => 'artist_invitations#add_nested_invitations'
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  # after_save :remove_data
  # after_save :add_education_table
  # after_save :add_custom_table
  # after_save :add_representation_table
  
  attr_accessor :columns, :positions, :custom_cols, :custom_pos, :repr_cols, :repr_pos

  scope :directors, -> {all.uniq}
  scope :artists,   -> {all}
  scope :performing_artist, -> { where resume_type: 'Performing Artist' }
  scope :production_member, -> { where resume_type: 'Production Member' }

  belongs_to :user
  has_many :roles, dependent: :destroy
  has_many :directed_roles, :class_name => "Role", :foreign_key => 'director_id'
  has_many :productions, :through => :roles
  has_many :directed_productions, :class_name => "Production", :foreign_key => 'director_id'
  has_many :section_slots, -> { order('position ASC') }, :dependent => :destroy
  # has_one  :education_table, :dependent => :destroy
  # has_one  :skill_list, :dependent => :destroy
  # has_many :rtables, :through => :section_slots, :dependent => :destroy
  has_many :rtables
  # has_many :custom_lists,  :dependent => :destroy
  has_one :resume_attribute,:class_name=>"Attribute", dependent: :destroy
  has_one :contact_info, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :theatres, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :representations, dependent: :destroy
  has_many :skills, dependent: :destroy  
  has_many :others, dependent: :destroy
  has_many :customs, dependent: :destroy
  has_many :resume_sections, dependent: :destroy
  has_many :videos, dependent: :destroy
  accepts_nested_attributes_for :resume_attribute,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :contact_info,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :photos,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :theatres,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :educations,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :representations,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :skills,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :others,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :customs,:allow_destroy => true, reject_if: :all_blank
  accepts_nested_attributes_for :resume_sections,:allow_destroy => true, reject_if: :all_blank

  accepts_nested_attributes_for :rtables,:allow_destroy => true, reject_if: :all_blank

  accepts_nested_attributes_for :roles, allow_destroy: true, reject_if: :all_blank
  delegate :name, :to => :user, :prefix => true

  validates :user, :presence => true
  validate :validate_resumes
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }#, :default_url => "../assets/blankUser.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  def validate_resumes
    if roles.any? && !roles[0].valid?
      # errors.clear
      errors.add(:role_name, roles[0].errors[:name].first)
    end
  end

  def name
    user.full_name
  end

  def remove_data
    Rtable.where(resume_id: id).destroy_all
    resume=Resume.find(id).section_slots
    resume.destroy_all if !resume.blank?
  end
  def add_education_table
    table = Rtable.create(title: 'Education', columns: '{'+self.columns+'}', positions: '{'+self.positions+'}', resume_id: id)
    SectionSlot.create(section_id: table.id, section_type: 'Rtable', resume_id: id, position: 1)
  end

  def add_custom_table
    table = Rtable.create(title: 'Custom', columns: '{'+self.custom_cols+'}', positions: '{'+self.custom_pos+'}', resume_id: id)
    SectionSlot.create(section_id: table.id, section_type: 'Rtable', resume_id: id, position: 1)
  end

  def add_representation_table
    table = Rtable.create(title: 'Representation', columns: '{'+self.repr_cols+'}', positions: '{'+self.repr_pos+'}', resume_id: id)
    SectionSlot.create(section_id: table.id, section_type: 'Rtable', resume_id: id, position: 1)
  end

  def add_rtable
    table = Rtable.create(title: 'Other', columns: '{Column 1,Column 2,Column 3,Column 4,Column 5,Column 6}', positions: '{1,2,3,4,5,6}')
    max_pos = SectionSlot.where('resume_id = ?', id).maximum("position")
    SectionSlot.create(section_id: table.id, section_type: 'Rtable', resume_id: id, position: max_pos + 1)
  end

  def to_param
    if !self.custom_url.nil?
	"#{custom_url}"
    else
	"#{id}"	
    end
  end 

end

app/helpers/resumes_helper.rb
require 'addressable/uri'
module ResumesHelper
	def education(e, cust=nil, repr=nil)
		slots_hash = Hash.new()
    if e.object.section_slots.present?
	    education=repr.present? ? e.object.section_slots.collect(&:section).last : cust.present? ? e.object.section_slots.collect(&:section).second : e.object.section_slots.collect(&:section).first
	    education.positions.collect{|p| slots_hash[p]=education.columns[education.positions.index(p)]} 
	  end
	  return slots_hash
	end

	def final_resume(e, cust)
		slots_hash = Hash.new()
    if e.section_slots.present?
	    education=cust.present? ? e.section_slots.collect(&:section).last : e.section_slots.collect(&:section).first
	    education.positions.collect{|p| slots_hash[p]=education.columns[education.positions.index(p)]}
	  end
	  return slots_hash
	end
	
	def embed(url)
	    # youtube_id = youtube_url.split("=").last
	    # content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
	    # yt_regexp = /^(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
	    # vimeo_regexp = /^http:\/\/www\.vimeo\.com\/(\d+)/
	    # https://youtu.be/QtHn55X1crM
	    # https://www.youtube.com/watch?v=QtHn55X1crM
	    # https://vimeo.com/117408881  
	    uri = Addressable::URI.parse(url)
	     if uri.host == "vimeo.com" 
	     	vimeo_id = uri.basename
	     	content_tag(:iframe,nil,src: "//player.vimeo.com/video/#{vimeo_id}") 

	     elsif uri.host == "www.youtube.com"
	     	youtube_id = url.split("=").last 
	        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")

	     elsif uri.host == "youtu.be" 
	     	 youtube_id = uri.basename
	     	 content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")  
	     end	
	 #    if uri.host == "vimeo.com" 
		#     AutoHtml.add_filter(:vimeo).with(:width => 440, :height => 248, :show_title => false, :show_byline => false, :show_portrait => false, :allow_fullscreen => false) do |url, options|
		# 		url.gsub(/https?:\/\/(www.)?vimeo\.com\/([A-Za-z0-9._%-]*)((\?|#)\S+)?/) do
		# 			vimeo_id = $2
		# 			width = options[:width]
		# 			height = options[:height]
		# 			show_title = "title=0" unless options[:show_title]
		# 			show_byline = "byline=0" unless options[:show_byline]
		# 			show_portrait = "portrait=0" unless options[:show_portrait]
		# 			allow_fullscreen = " webkitallowfullscreen mozallowfullscreen allowfullscreen" if options[:allow_fullscreen]
		# 			frameborder = options[:frameborder] || 0
		# 			query_string_variables = [show_title, show_byline, show_portrait].compact.join("&")
		# 			query_string = "?" + query_string_variables unless query_string_variables.empty?
		# 			%{<iframe src="//player.vimeo.com/video/#{vimeo_id}#{query_string}" width="#{width}" height="#{height}" frameborder="#{frameborder}"#{allow_fullscreen}></iframe>}
		# 		end
		# 	end
		# elsif uri.host == "www.youtube.com" || uri.host == 'youtu.be'
			# AutoHtml.add_filter(:youtube).with(:width => 420, :height => 315, :frameborder => 0, :wmode => nil, :autoplay => false, :hide_related => false) do |"https://www.youtube.com/watch?v=QtHn55X1crM", options|
			# 	regex = /(https?:\/\/)?(www.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/watch\?feature=player_embedded&v=)([A-Za-z0-9_-]*)(\&\S+)?(\?\S+)?/
			# 		url.gsub(regex) do
			# 		youtube_id = $4
			# 		width = options[:width]
			# 		height = options[:height]
			# 		frameborder = options[:frameborder]
			# 		wmode = options[:wmode]
			# 		autoplay = options[:autoplay]
			# 		hide_related = options[:hide_related]
			# 		src = "//www.youtube.com/embed/#{youtube_id}"
			# 		params = []
			# 		params << "wmode=#{wmode}" if wmode
			# 		params << "autoplay=1" if autoplay
			# 		params << "rel=0" if hide_related
			# 		src += "?#{params.join '&'}" unless params.empty?
			# 		%{<div class="video youtube"><iframe width="#{width}" height="#{height}" src="#{src}" frameborder="#{frameborder}" allowfullscreen></iframe></div>}
			# 	end
			# end
		# end	
	end

	def get_venue_and_company(role)
		venue = role.production_current_venue
		company = role.production_company
		if venue.present? && company.present?
       		link_to(role.production_current_venue_name,venue_path(venue.id),:target=>"_blank") +" - " +link_to(role.production_company_name,company_path(company.id),:target=>"_blank")
        elsif role.production_current_venue.present?  
            link_to(role.production_current_venue_name,venue_path(venue.id),:target=>"_blank")
        else
           link_to(role.production_company_name,company_path(company.id),:target=>"_blank")
        end
               
	end	

	def show_image(resume)
		if resume.resume_type == 'Performing Artist'
			if resume.image.file?
	          image_tag resume.image.try(:url),:style=>"width: 250px;"
	        else
	          content_tag(:div,:class=>"resume_attribute") do	
	          	render 'resumes/show_contact_info',:@resume=>resume		
	          end	
	        end	
	    end
	        
	end	

	def show_attribute(resume)
		if resume.resume_type == 'Performing Artist'
			 render 'resumes/show_attribute',:@resume=>resume
		elsif resume.resume_type == 'Production Member' || resume.resume_type == 'Director'
			if resume.image.file?
			 render 'resumes/show_contact_info',:@resume=>resume
			end 	
		end	
	end	


    def get_title_row_class(index)
    	index == 0 ? "col-xs-2 diminished-font m-bottom-20" : "col-xs-2"
    end

    def get_title_row_bold(index)
    	index == 0 ? "bold_col" : ""
    end	

end

app/views/resumes/_load_form_json.html.erb
<% productions_name= get_productions_name %>
<% venues_name= get_venues_name %>
<% companies_name= get_companies_name %>
<% directors_name= get_directors_name %>
<script type="text/javascript">
 $(function() {
    $('body').click(function() {
        var productionsArray = <%=  raw productions_name%>;
        var venuesArray = <%=  raw venues_name%>;
        var companiesArray = <%=  raw companies_name%>;
        var directorsArray = <%=  raw directors_name%>;
      if(jQuery.inArray($(".productions_name").val(),productionsArray) == -1){
        $(".productions_name").val("")
        // the element is not in the array
    };

    if(jQuery.inArray($(".venues_name").val(),venuesArray) == -1){
        $(".venues_name").val("")
        // the element is not in the array
    };

    if(jQuery.inArray($(".company_name").val(),companiesArray) == -1){
        $(".company_name").val("")
        // the element is not in the array
    };

    if(jQuery.inArray($(".director_name").val(),directorsArray) == -1){
        $(".director_name").val("")
        // the element is not in the array
    };
     $('#add-new-production').hide();
     $('#add-new-company').hide();
     $('#add-new-venue').hide();
     $('#add-new-director').hide();
  });
  });

$('body').click(function() {
   $('#productions_name').trigger("focus"); //or "click", at least one should work
});
  </script>

app/views/resumes/_more_videos.html.erb
<% if @videos.present? %>
    <% @videos.each do |video| %>
    <div class="more-videos">
    <%= embed(video.video_url) %>
    <%= link_to image_tag("edit_delete.png"),"javascript:void(0)",:class=>"video_#{video.id}" %>
    <script>
      $(document).on('click','.video_<%=video.id%>',function(){
        $.ajax({
          url: '<%=destroy_resume_video_path(video.id)%>',
          dataType: 'script',
          method: 'delete'
        });
      });
    </script>
    </div>
  <%end%>
  
<%end%>

app/views/resumes/_photo_priview.html.erb
<%= image_tag @image.image.url %>

app/views/resumes/_print_popup.html.erb
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="printModal" class="modal ">
  <div class="modal-dialog">
    <div class="modal-content">
       <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">
                ×
          </button>
          <h4 id="myModalLabel" class="modal-title">
            Print Resume
          </h4>
       </div>
       <div class="modal-body">
        <h5>
          NOTE: Your printed Resume will only show the text that fits on 1 sheet of paper (8 x 10 for Performing Artists and 8 1/2 x 11 for Production Members or Directors) so if your current Resume is longer than 1 page and you do not have a premium account, Artist Magnet recommends you upgrade and create an additional Resume that fits into the 1 page printable format, or upgrade to print all of your pages. <%=link_to "Click here to upgrade.","/resumes/account_tier", :target => "_blank"%>
        </h5>
       </div>
       <div class="modal-footer">
          <div class="hide" style="width:100%;height:100%"><iframe src="<%=resume_path(@resume,:print=>true)%>" name="frame" id="resume_frame"></iframe>
          <iframe name="myFrame" width="100%" height="400" id="my_frame"></iframe>

          </div>
          <%#= link_to "Print", '#', onclick: "frames['frame'].print()",:class=>"btn btn-default "%>
          <%= link_to "Print", '#', onclick: "PrintDoc()",:class=>"btn btn-default "%>
          <%= link_to "Print Preview", download_pdf_resume_path(@resume.id,:format=>"pdf"),:class=>"btn btn-default "%>
          <%= link_to "Go Back", resumes_path,:class=>"btn btn-default "%>
       </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal -->
</div>
<script type="text/javascript">
   function PrintDoc() {
    var data = document.getElementById("resume_frame").contentWindow.document.body.innerHTML;
     // var mywindow = window.open('', 'printMe', 'left=50000,top=50000,width=0,height=0');
     var mywindow = window.frames["myFrame"];
     var layout_path = "<%= asset_path 'templates/layouts' %>";
     var main_path = "<%= asset_path 'templates/main' %>";
     var custom_path = "<%= asset_path 'templates/custom'%>";
     var bootstrap_path = "<%= asset_path 'templates/bootstrap.min'%>";
     var resumes_path = "<%= asset_path 'resumes'%>";

     mywindow.document.write('<html><head><link href="'+layout_path+'" rel="stylesheet" type="text/css" media="all"/><link href="'+main_path+'" rel="stylesheet" type="text/css" media="all"/><link href="'+custom_path+'" rel="stylesheet" type="text/css" media="all"/><link href="'+bootstrap_path+'" rel="stylesheet" type="text/css" media="all"/><link href="'+resumes_path+'" rel="stylesheet" type="text/css" media="all"/><title>Print Me</title>');
     mywindow.document.write('</head><body >');
     mywindow.document.write(data);
     mywindow.document.write('</body></html>');
     mywindow.document.close();

     mywindow.focus();
     mywindow.print();
     mywindow.close();

     return true;

    }
</script>

app/views/resumes/_section_slot.html.erb
<div class="row" id="section_slot_<%= section_slot.id %>">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row m-bottom-20">
          <div class="col-md-12">
            <i class="fa fa-arrows pull-right text-pale top-right-handle"></i>
            <h4>
              <span><%= section_slot.section.title %></span>
              <% if section_slot.section.type.nil? %>
                <%= link_to destroy_resume_table_path(section_slot.resume_id, section_slot.section), method: :delete do %>
                  <button type="button" class="btn btn-primary pull-right m-top-m6 m-left-6">Delete</button>
                <% end %>
              <% end %>
              <%= link_to edit_polymorphic_path(section_slot.section) do %>
              <!--< %= link_to edit_education_table_path(section_slot.section) do %>-->
                <button type="button" class="btn btn-primary pull-right m-top-m6">Edit</button>
              <% end %>
            </h4>
            <br>
            <%= render partial: 'rtables/columns', locals: {table: section_slot.section} %>

            <% section_slot.section.rtable_items.each do |line| %>
              <div class="h-movable row">
                <% line.values.each do |cell| %>
                  <div class="col-md-2">
                    <%= cell %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resumes/add_videos.js.erb
$(".more-video").html("<%=escape_javascript(render 'resumes/more_videos',:@videos=>@videos)%>");

app/views/resumes/create_role.js.erb
// $('.role_fields').html("<%= escape_javascript render('resumes/nested/theatre_data',:@roles=>@roles) %>");
// $('.flash-message').html("<%= escape_javascript render('layouts/includes/notice') %>");
$('.threatr-section > li.sortable').html("<%= escape_javascript render('resumes/nested/theatre_data',:@roles=>@roles) %>");

app/views/resumes/edit_with_role.html.erb
<%= render 'form', role_visibility: 'block' %>

app/views/resumes/new.html.erb
<%= render 'form' %>
<script>
$(window).bind("pageshow", function() { 
  $('#new_resume')[0].reset(); 
});
</script>

app/views/resumes/new_theatre.js.erb
$(".photo-popover1").hide();
$('.add_new_theatre').append("<%= escape_javascript render('resumes/nested/new_theatre') %>");

app/views/resumes/show_resume_pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <!-- <meta name="pdfkit-orientation" content="Landscape"/> -->
    <style type="text/css" media="print">
      <% if @resume.resume_type == 'Performing Artist' %>
        @page {
          size: 8in 10in; 
          
        }
        body{
          margin: .25in .75in 1.25in .25in;
          /*writing-mode: tb-rl;*/
        }
      <%else%>
        @page {
          size: 8.5in 11in; 
          
        }
        body{
          margin: 1in 1in 1in 1in;
          /*writing-mode: tb-rl;*/
        }
      <%end%>
  </style>
  </head>
    <body>
<div class="container-fluid m-top-20">
  
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body" id="show-resume">         
          <section class="list-resumes">            
            <div class="row">
                
              <div class="col-xs-3 resume_attribute">
               <%= show_attribute(@resume)%>
               
               </div>

               
              <div class="col-xs-5 contact_block">
                 <h2><%=@resume.contact_info.nick_name.upcase%></h2>
                 <% if @resume.try(:performer_type).present?%>
                  <h4><%=@resume.try(:performer_type).upcase%></h4>
                 <%end%>
                 <% if @resume.try(:union_guild).present?%>
                  <h5><%=@resume.try(:union_guild).upcase%></h5>
                <%end%>

                <br/>
                 <% if (@resume.image.file? && @resume.resume_type == 'Performing Artist') || ( !@resume.image.file? && (@resume.resume_type == 'Production Member' || @resume.resume_type == 'Director'))%>
 
                  
                
                  
                   <%= render 'resumes/show_contact_info',:@resume=>@resume%>
                 <%end%>
                
               </div>

                <div class="col-xs-4 image_section">
                 <%=show_image(@resume)%>
               </div>
              
                
             </div>
                   
            </section>
          
            <!-- <hr/> -->
             <% if @resume.representations.present? %>
             <section class="list-resumes">
              <div class="row">
                <strong><div class="col-xs-2"><%=@resume.resume_sections.where(:section_id=>1).first.try(:section_name)%>:</div></strong>
              
                     <% @resume.representations.each do |representation|%>
                     
                      
                      <div class="col-xs-10 area_text"><%= h representation.rcolumns %></div>
                      
              </div>
                      <%end%>                 
              </section>

              <br />
              <%end%>
              



            <section class="list-resumes">
              <strong>Theatre</strong>
              <%=render 'resumes/nested/theatre_fields'%>
                <% @resume.roles.each do |theatre|%>
                <div class="row">
                  <div class="col-xs-3"><%= link_to theatre.production_name.upcase,theatre.production ,:target=>"_blank" if !theatre.production.blank?%></div>
                  <div class="col-xs-2"><%= theatre.name.capitalize%></div>
                  <div class="col-xs-2"><%= theatre.director_name.capitalize%></div>
                  <div class="col-xs-4"><%= get_venue_and_company(theatre) %></div>
                </div>
                <%end%>
              
            </section ><br/>
            
            
            <% if @resume.educations.present? %>
            <section class="list-resumes">
              <strong><%=@resume.resume_sections.where(:section_id=>2).first.try(:section_name)%></strong>
              
                   <% @resume.educations.each_with_index do |education,index|%>
                    <div class="row">
                      <% education.ecolumns.each do |col|%>
                      <div class="<%=get_title_row_class(index)%>" id="<%=get_title_row_bold(index)%>"><%= col %></div>
                      <%end%>
                    </div> 
                    <%end%>                 
            </section>
            <br/>
          <%end%>
            
            <% if @resume.skills.present? %>
              <section class="list-resumes">
                <strong><%=@resume.resume_sections.where(:section_id=>3).first.try(:section_name)%></strong>
                <div class="area_text">
                  <%= h @resume.skills.map { |tag| tag.skills.capitalize }.join(', ')  if !@resume.skills.blank?%>
                      
                 </div>
              </section><br />
            <%end%>  

              <% if @resume.customs.present? %>
              <section class="list-resumes">
              <strong><%=@resume.resume_sections.where(:section_id=>4).first.try(:section_name)%></strong>
             
                  <%#=render 'resumes/nested/final_education_fields',:e=>@resume,:cust=>"custom"%>
                   <% @resume.customs.each_with_index do |custom,index|%>
                    <div class="row">
                     <% custom.ccolumns.each do |col|%>
                      <div class="<%=get_title_row_class(index)%>" id="<%=get_title_row_bold(index)%>"><%= col %></div>
                      <%end%>
                    </div> 
                    <%end%>
            </section><br/>
            <%end%>

            <% if @resume.others.present? %>
            <section class="list-resumes">
              <strong><%=@resume.resume_sections.where(:section_id=>5).first.try(:section_name)%></strong>
                <div class="area_text">
                   <%= h @resume.others.map { |tag| tag.content }.join(', ')  if !@resume.others.blank?%>
                </div>
           
            </section><br />
            <%end%>

            </div>
            
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" id="section_slot" data-update-url="<%= sort_section_slots_url %>">
  <%# @resume.section_slots.each do |section_slot| %>
    <%#= render partial: 'section_slot', locals: {section_slot: section_slot} %>
  <%# end %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <!--<button type="button" class="btn btn-primary m-top-m6">Add a skills section</button>-->
      <%#= link_to add_resume_table_path(@resume), method: :post do %>
        <!-- <button type="button" class="btn btn-primary m-top-m6">Add a custom section</button> -->
      <%# end %>
    </div>
  </div>
</div>
</body>
</html>